### PR TITLE
feat: Add intermediate List/Set decode

### PR DESCRIPTION
**Pull request by Iltotore**
Allow intermerdiate decoding of `List[T]` and `Set[T]` exprs, enabling compile-time support for all `collection` constraints and making `Length` more flexible.

### CODE REVIEW

**Comment by mio-19** [comment]
What about Vector and Seq.apply

**Comment by mio-19** [comment]
I used many Vector in my codebase

**Comment by Iltotore** [comment]
@mio-19 though you are not supposed to directly use `Vector` in your code base except for some special cases, yes it is possible to support `Seq.apply` and `Vector.apply` in compile-time refinement the same way this PR does for List and Set. I'll be glad to review a PR for it.

**Comment by mio-19** [comment]
> @mio-19 though you are not supposed to directly use `Vector` in your code base except for some special cases

What's the reason for that? I would like to know more about this.

**Comment by Iltotore** [comment]
> > @mio-19 though you are not supposed to directly use `Vector` in your code base except for some special cases
> 
> What's the reason for that? I would like to know more about this.

@mio-19 AFAIK it is because it's not the "best-complexity-overall" `List` implementation so not the one to use by default. People usually use `List.apply` and `Set.apply` instead because they (the underlying implementation) were made for the general case.

**Pull request merged**
