### PR TITLE
feat: Support for ciris

### PR DESCRIPTION
**Pull request by rparree**
I was using a generic implicit to use iron with [ciris](https://cir.is/). It works fine for me.  I have added a test, which is mostly a smoke test to see that it works. It does however perform a proper summon of a `ciris.ConfigDecoder`

let me know what else to do/change.

### CODE REVIEW

**Comment by Iltotore** [comment]
Looks good to me but wouldn't it be better to be added to the Ciris repository?

For example, this is already the case of Refined support.

**Comment by rparree** [comment]
That's also possible, however i thought it fitted nice with ciris support. But you're right it might be better suited over there. Let' me check

**Comment by Iltotore** [comment]
I'm leaving this PR open in case Ciris maintainers can't or don't want to support Iron in their repository.

**Comment by rparree** [comment]
https://github.com/vlovgr/ciris/pull/692

**Comment by Iltotore** [comment]
@rparree I think we will finally merge your PR in this repository because of the encountered issues. I will just wait for #175 to be merged first.

Sorry for the delay :sweat_smile:

**Pull request merged**
