### PR TITLE
add cats typeclass instances

### PR DESCRIPTION
**Pull request by gvolpe**
- The package `catsSupport` was renamed to `cats`.
- The package `circeSupport` was renamed to `circe`.
- [Package objects will be deprecated and removed soon](https://docs.scala-lang.org/scala3/reference/dropped-features/package-objects.html), so these are now objects.
- A bit of documentation was added for the usage of Cats instances.

I'm not familiar enough with `mill` so I didn't know how to build the documentation locally, but I tested the examples.

### CODE REVIEW

**Comment by Iltotore** [comment]
Good job. Can you also rename the `zioJsonSupport` package to `zioJson`?

**Review by Iltotore — CHANGES_REQUESTED** [review]
Can you rename the package `zioJsonSupport` to `zioJson`?

**Comment by gvolpe** [comment]
Sure, forgot to comment I wasn't sure what you wanted to do with that one, so I left it.

**Review by Iltotore — APPROVED** [review]
Looks good to me.

**Comment by gvolpe** [comment]
@Iltotore whenever you have some time, may I ask you to release a snapshot/milestone or another RC? Thank you!

**Comment by Iltotore** [comment]
A new one with (probably) SJS/SN support will be released the next week or this weekend if possible.

**Pull request merged**
